//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distributor.DTO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueDetail
    {
        public int ProId { get; set; }
        public int SellerId { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Remainder { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
