//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distributor.DTO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int SellerId { get; set; }
        public System.DateTime DateOfIssue { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Debt { get; set; }
    
        public virtual Seller Seller { get; set; }
    }
}
