//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distributor.DTO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.IssueDetails = new HashSet<IssueDetail>();
            this.Stocks = new HashSet<Stock>();
            this.Sales = new HashSet<Sale>();
            this.SellerSales = new HashSet<SellerSale>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Sale { get; set; }
        public Nullable<int> CatId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<IssueDetail> IssueDetails { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual ICollection<SellerSale> SellerSales { get; set; }
    }
}
