//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unilever.DTO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedRegister
    {
        public int ProId { get; set; }
        public int DistributorId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Distributor Distributor { get; set; }
        public virtual Product Product { get; set; }
    }
}
