//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seller.DTO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Remainder { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<int> CusId { get; set; }
        public Nullable<int> IsFixed { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
    }
}
