//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seller.DTO.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int OrderId { get; set; }
        public System.DateTime PayDate { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> Remainder { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
